server:
  port: 10010
spring:
  cloud:
    gateway:
      routes:
      - id: tps_route
        uri: lb://TPS-service
        predicates:
        - Path=/tps/**
        filters:
        - StripPrefix=1
        order: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka